[keys]
quit = ["q", "esc"]

[[actions]]
name = "copy-change-id"
lua = '''
copy_to_clipboard(context.change_id())
flash("Copied: " .. context.change_id())
'''

[[actions]]
name = "difft"
lua = '''diff.show(jj({ "difft", "-r", context.change_id(), context.file() }))'''

[[bindings]]
action = "copy-change-id"
key = "y"
scope = "revisions"
desc = "copy change id"

[[bindings]]
action = "difft"
key = "t"
scope = "revisions"
desc = "difft"

[[bindings]]
action = "difft"
key = "t"
scope = "revisions.details"
desc = "difft"

[ui.colors]
selected = { bg = "#272a36" }
