theme = "mourning"

[editor]
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint" # TODO may be enabled by default in future
lsp.auto-signature-help = false
scroll-lines = 1
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

# TODO new inline diagnostics config, disabled by default but enabled in future:
[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
right = [
  "diagnostics",
  "register",
  "selections",
  "separator",
  "file-encoding",
  "file-type",
  "separator",
  "spacer",
  "position-percentage",
  "position",
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Cmd-s = ":write"
Cmd-z = ":reset-diff-change"
# TODO trying this out; do I need these, or should I just swap to select mode?
C-j = ["select_line_below"]
C-k = ["select_line_above"]

# vim helpers
Z = { Z = ":write-quit" }
C-e = "scroll_down"
C-y = "scroll_up"
# TODO replace { / } with [p / ]p followed by A-. (repeat last motion)
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection_detect_word_boundaries",
  "search_next",
]

# TODO: remove these nags once I get used to it
# A-c = ":sh echo '-> C (A-c is change selection noyank)'"
C-r = ":sh echo '-> U'"
D = ":sh echo '-> t<ret>d'"
G = [":sh echo '-> ge'", "goto_line"] # TODO remove this, it's built in

[keys.normal.space]
o = ":sh echo '--> <space>F'"                 # TODO remove; this is built in
x = ":buffer-close"
F = "file_picker_in_current_buffer_directory" # TODO consider: default is current_directory, but this is more useful

[keys.insert]
Cmd-s = ":write"
C-c = "signature_help" # hidden by default, this makes C-c a toggle

[keys.select]
# vim helpers
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
