theme = "mourning"

[editor]
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint" # TODO may be enabled by default in future
lsp.auto-signature-help = false
scroll-lines = 1
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

# TODO new inline diagnostics config, disabled by default but enabled in future:
[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
right = [
  "diagnostics",
  "register",
  "selections",
  "separator",
  "file-encoding",
  "file-type",
  "separator",
  "spacer",
  "position-percentage",
  "position",
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Cmd-s = ":write"
Cmd-z = ":reset-diff-change"

A-c = "copy_selection_on_next_line" # replace helix `C` bind

# vim helpers; I should be getting used to helix, but these are too ingrained
C-r = "redo"
C-e = "scroll_down"
C-y = "scroll_up"
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
G = "goto_file_end"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]

# TODO trying this out; do I need these, or should I just swap to select mode?
C-j = ["select_line_below"]
C-k = ["select_line_above"]

[keys.normal.space]
x = ":buffer-close"

[keys.normal.Z]
Z = ":write-quit"

[keys.insert]
Cmd-s = ":write"
C-c = "signature_help"
