theme = "mourning"

[editor]
bufferline = "multiple"
color-modes = true
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
completion-timeout = 5
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"
lsp.auto-signature-help = false
scroll-lines = 1
soft-wrap.enable = true
statusline.right = [
  "diagnostics",
  "register",
  "selections",
  "separator",
  "file-encoding",
  "file-type",
  "separator",
  "spacer",
  "position-percentage",
  "position",
]

[keys.normal]
Cmd-s = ":write"
Cmd-z = ":reset-diff-change"
C-j = "select_line_below"
C-k = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

# vim helpers
Z = { Z = ":write-quit" }
C-e = "scroll_down"
C-y = "scroll_up"
g = { q = ":reflow" }
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection_detect_word_boundaries",
  "search_next",
]

[keys.normal.space]
B = ":echo %sh{jj file annotate %{buffer_name} -T blame | sed -n %{cursor_line}p}"
F = "file_picker_in_current_buffer_directory"
j = ":sh zellij run -ic -n jjui -- jjui ."
J = [":write-all", ":sh zellij run -ic -n jjui -- jjui .", ":reload-all"]
x = ":buffer-close"

[keys.normal.tab]
h = ":toggle-option file-picker.hidden"
i = ":toggle-option file-picker.git-ignore"
w = ":toggle-option whitespace.render all none"

[keys.insert]
Cmd-s = ":write"
C-c = "signature_help" # hidden by default, this makes C-c a toggle

[keys.select]
# vim helpers
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
