#!/usr/bin/perl
use warnings;
use strict;

use YAML;

my %mail_order = (
    home => 0,
    work => 1,
    other => 2,
);

# sort { $order{$a} <=> $order{$b} } keys %$f

# Slurp all of stdin at once.
my $contacts = do { local $/; YAML::Load(<>) };

for my $person (@$contacts) {
  my $name = $person->{'fn'} . ($person->{'ln'} ? ' ' . $person->{'ln'} : '');
  my $mail = $person->{'mail'};
  next unless $name && $mail;

  my $alias = $person->{'alias'};
  unless ($alias) {
    $alias = lc $name;
    $alias =~ s/[^a-z]/-/g;
  }

  my @addrs = ref $mail ? values %$mail : ($mail);
  my $suffix = 0;
  for my $addr (@addrs) {
    printf "alias %s%s\t%s <%s>\n",
      $alias, ($suffix++ ? $suffix : ''), $name, $addr;
  }
}
